name: CI

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    container: opendistroforelasticsearch/security-maven:v1

    steps:

      - name: Checkout
        uses: actions/checkout@v1

      - name: Install
        run: mvn clean install
